name:                coding-interview
version:             0.1.0.0
github:              "YusukeHosonuma/coding-interview"
license:             BSD3
author:              "Yusuke Hosonuma"
maintainer:          "tobi462@gmail.com"
copyright:           "(c) 2019 Yusuke Hosonuma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YusukeHosonuma/coding-interview#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  coding-interview-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coding-interview

tests:
  coding-interview-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coding-interview
